modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="${issue_tracker_url}"
logoFile="icon.png"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL=""
authors="$mod_author"
description='''${description}'''

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="SERVER"

[[dependencies.${mod_id}]]
modId="obsidianweave"
mandatory=true
versionRange="${obsidianweave_version_range}"
ordering="AFTER"
side="SERVER"